// client/src/components/Modal.tsx
import { useEffect, useId, useRef } from "react";

type ModalProps = {
	onClose: () => void;
	header?: React.ReactNode;
	main?: React.ReactNode;
	footer?: React.ReactNode;
};

export default function Modal(props: ModalProps) {
	const id = useId();
	const modalRef = useRef<HTMLDivElement>(null);

	const handleClick = (event: MouseEvent) => {
		if (modalRef.current && !modalRef.current.contains(event.target as Node)) {
			props.onClose();
		}
	};

	const handleKeydown = (event: KeyboardEvent) => {
		if (event.key === "Escape") {
			props.onClose();
		}
	};

	useEffect(() => {
		document.addEventListener("mousedown", handleClick, true);
		document.addEventListener("keydown", handleKeydown);

		return () => {
			document.removeEventListener("mousedown", handleClick, true);
			document.removeEventListener("keydown", handleKeydown);
		};
	}, [props.onClose]);

	return (
		<div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
			<div
				id={id}
				className="bg-white border border-stone-300 rounded-lg shadow-md min-w-[250px] min-h-[180px] max-w-full max-h-full overflow-auto"
				role="dialog"
				tabIndex={-1}
				ref={modalRef}
			>
				{props.header && <header>{props.header}</header>}
				<main>{props.main}</main>
				{props.footer && <footer>{props.footer}</footer>}
			</div>
		</div>
	);
}

// src/components/Modal/Modal.tsx
import { component$, useSignal, Slot } from "@builder.io/qwik";
import { useVisibleTask$ } from "@builder.io/qwik";
import type { PropFunction } from "@builder.io/qwik";

export interface ModalProps {
  isOpen: boolean;
  onClose$: PropFunction<() => void>;
  title?: string;
}

export const Modal = component$<ModalProps>(({ isOpen, onClose$, title }) => {
  const dialogRef = useSignal<HTMLDialogElement | undefined>();

  useVisibleTask$(({ track }) => {
    track(() => isOpen);

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && isOpen) {
        onClose$();
      }
    };

    const handleClickOutside = (event: MouseEvent) => {
      if (dialogRef.value && event.target instanceof Node) {
        if (event.target === dialogRef.value) {
          onClose$();
        }
      }
    };

    if (isOpen) {
      dialogRef.value?.showModal();
      document.addEventListener("keydown", handleKeyDown);
      dialogRef.value?.addEventListener("click", handleClickOutside);
    } else {
      dialogRef.value?.close();
    }

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      dialogRef.value?.removeEventListener("click", handleClickOutside);
    };
  });

  return (
    <>
      {isOpen && (
        <dialog
          ref={dialogRef}
          class="fixed inset-0 z-50 m-auto rounded-lg border border-solid border-gray-300 bg-white shadow-md"
        >
          {title && <header class="flex gap-5 border-b border-solid border-gray-300 p-4">
            <h2 class="text-xl font-semibold">{title}</h2>
            <button class="ml-auto hover:cursor-pointer" onClick$={onClose$}>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#000000"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M18 6 6 18"></path>
                <path d="m6 6 12 12"></path>
              </svg>
            </button>
          </header>}
          <main class="p-5">
            <Slot />
          </main>
        </dialog>
      )}
    </>
  );
});
