// src/lib/components/Modal.svelte
<script lang="ts">
  import { tick, type Snippet } from "svelte"

  let {
    onclose = () => {},
    main,
    header,
    footer
  }: {
    onclose: () => void
    main: Snippet
    header?: Snippet
    footer?: Snippet
  } = $props()

  let id = $props.id()

  let modalRef: HTMLElement
  const modalStack: HTMLElement[] = ((window as any).modalStack ??= [])

  function handleClick(event: MouseEvent) {
    if (modalStack[modalStack.length - 1] === modalRef) {
      if (!modalRef.contains(event.target as Node)) {
        onclose()
      }
    }
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === "Escape" && modalStack[modalStack.length - 1] === modalRef) {
      onclose()
    }
  }

  $effect(() => {
    modalStack.push(modalRef)

    tick().then(() => {
      document.addEventListener("mousedown", handleClick, true)
      document.addEventListener("keydown", handleKeydown)
    })

    return () => {
      const index = modalStack.indexOf(modalRef)
      if (index !== -1) {
        modalStack.splice(index, 1)
      }
      document.removeEventListener("mousedown", handleClick, true)
      document.removeEventListener("keydown", handleKeydown)
    }
  })
</script>

<div class="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
  <div
    {id}
    class="bg-white border border-solid border-stone-300 rounded-lg shadow-md min-w-[200px] min-h-[150px] max-w-full max-h-full overflow-auto"
    role="dialog"
    aria-modal="true"
    tabindex="-1"
    bind:this={modalRef}
  >
    {#if header}
      <header>
        {@render header()}
      </header>
    {/if}

    <main>
      {@render main()}
    </main>

    {#if footer}
      <footer>
        {@render footer()}
      </footer>
    {/if}
  </div>
</div>

// client/src/components/Modal.tsx
import { useEffect, useId, useRef } from "react";

type ModalProps = {
	onClose: () => void;
	header?: React.ReactNode;
	main?: React.ReactNode;
	footer?: React.ReactNode;
};

export default function Modal(props: ModalProps) {
	const id = useId();
	const modalRef = useRef<HTMLDivElement>(null);

	const handleClick = (event: MouseEvent) => {
		if (modalRef.current && !modalRef.current.contains(event.target as Node)) {
			props.onClose();
		}
	};

	const handleKeydown = (event: KeyboardEvent) => {
		if (event.key === "Escape") {
			props.onClose();
		}
	};

	useEffect(() => {
		document.addEventListener("mousedown", handleClick, true);
		document.addEventListener("keydown", handleKeydown);

		return () => {
			document.removeEventListener("mousedown", handleClick, true);
			document.removeEventListener("keydown", handleKeydown);
		};
	}, [props.onClose]);

	return (
		<div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
			<div
				id={id}
				className="bg-white border border-stone-300 rounded-lg shadow-md min-w-[250px] min-h-[180px] max-w-full max-h-full overflow-auto"
				role="dialog"
				tabIndex={-1}
				ref={modalRef}
			>
				{props.header && <header>{props.header}</header>}
				<main>{props.main}</main>
				{props.footer && <footer>{props.footer}</footer>}
			</div>
		</div>
	);
}
